#服务启动短信口号
server:
  port: 8081
  servlet:
    context-path: /volunteer
#数据连接
spring:
  datasource:
    url: jdbc:mysql://47.103.5.82:3306/volunteerDB?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Abc123!_
    driverCdrlassName: com.mysql.jdbc.Driver
#Mybatis扫描
mybatis:
  mapper-locations:
  - classpath*:mapper/*.xml
  type-aliases-package: com.volunteer.model