server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://47.103.5.82:3306/volunteerDB?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Abc123!_
    driverCdrlassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DatebookHikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 124.156.180.89
    port: 6379
    timeout: 1000
    password: dingwei123456
    max-active: 20
    max-idle: 50
    min-idle: 20
    max-wait: 5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  #静态资源对外暴露的访问路径
  mvc:
    stastatic-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload/,file:/upload
  servlet:
    multipart:
      max-file-size: -1
        

mybatis:
  mapper-locations:
  - classpath*:mapper/*.xml
#在application.yml文件中引入日志配置文件  
logging:
  config: classpath:config/logback.xml