server:
  port: 8081
  servlet:
    context-path: /volunteer
spring:
  datasource:
    url: jdbc:mysql://47.103.5.82:3306/volunteerDB?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Abc123!_
    driverCdrlassName: com.mysql.jdbc.Driver
  redis:
    host: 124.156.180.89
    port: 6379
    timeout: 1000
    password: dingwei123456
    max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 50 # 连接池中的最大空闲连接
    min-idle: 20 # 连接池中的最小空闲连接
    max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制
mybatis:
  mapper-locations:
  - classpath*:mapper/*.xml
  type-aliases-package: com.volunteer.model
